modApacheDeny_15Watt_dbHost database_host
modApacheDeny_15Watt_dbUser database_user
modApacheDeny_15Watt_dbPwd database_password
modApacheDeny_15Watt_dbPort database_port
modApacheDeny_15Watt_database database_name
modApacheDeny_15Watt_tableAddresses database_tabe_name_addresses_to_block
modApacheDeny_15Watt_tableUserAgents database_tabe_name_user_agents_to_block
modApacheDeny_15Watt_allowEmptyUserAgent false/true
